'use client';
import {withBase} from '@/lib/base-path';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Leaf} from 'lucide-react';
const pages=[
 {label:'The cover',heading:<>Every little world<br/>has a <em>story.</em></>,text:'Open our field journal. A few notes on nature, small details and the worlds we make.'},
 {label:'01 / Our beginning',heading:<>A little closer<br/>to <em>nature.</em></>,text:'A terrarium is an invitation to slow down. A moment of green, right where you are.'},
 {label:'02 / Our craft',heading:<>Small details.<br/><em>Lasting wonder.</em></>,text:'Glass, stone, earth and plants. Simple ingredients, thoughtfully brought together.'},
 {label:'03 / Made personal',heading:<>Your space.<br/>Your <em>story.</em></>,text:'Find a ready-made little world, or imagine one around your own space and style.'},
 {label:'The back cover',heading:<>The next chapter<br/>is <em>yours.</em></>,text:'A desk companion. A thoughtful gift. A little wilderness to call your own.'}
];
export default function AboutDiary(){const root=useRef<HTMLElement>(null),book=useRef<HTMLDivElement>(null);const [active,setActive]=useState(0);
 useEffect(()=>{const el=root.current;if(!el)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const update=()=>{const r=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,-r.top/(r.height-innerHeight)));const x=p*4.8;const index=Math.min(4,Math.floor(x));setActive(index);book.current?.querySelectorAll<HTMLElement>('.diary-sheet').forEach((sheet,i)=>{const t=Math.max(0,Math.min(1,(x-i-.48)/.48));const ease=t*t*(3-2*t);sheet.style.transform=`rotateY(${-180*(reduced.matches?(x>=i+1?1:0):ease)}deg)`;sheet.style.zIndex=String(i<index?i:10-i);sheet.style.opacity=String(reduced.matches?(x>=i+1?0:1):1-Math.max(0,Math.min(1,(t-.72)/.28)));sheet.style.pointerEvents='none';});};const scroll=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update)};update();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll)}},[]);
 const go=(i:number)=>{const el=root.current;if(el)window.scrollTo({top:el.offsetTop+(el.offsetHeight-innerHeight)*((i+.15)/4.8),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 return <section className="diary-section" id="about" ref={root}><div className="diary-sticky"><div className="diary-intro"><p className="eyebrow">THE TERRARIUM FIELD JOURNAL</p><div key={active} className="diary-story"><span className="diary-chapter">{pages[active].label}</span><h2>{pages[active].heading}</h2><p>{pages[active].text}</p></div><a href={withBase("/shop")} className="text-link">Find your little world <ArrowRight size={17}/></a><div className="diary-controls"><button aria-label="Previous journal page" disabled={active===0} onClick={()=>go(active-1)}><ArrowLeft size={18}/></button><span>0{active+1} / 05</span><button aria-label="Next journal page" disabled={active===4} onClick={()=>go(active+1)}><ArrowRight size={18}/></button></div></div><div className="diary-stage"><div className="diary-book" ref={book}>
 <div className="diary-back-cover" aria-hidden={active!==4}><span className="diary-edition">A WORLD WITHIN.</span><Leaf size={38} strokeWidth={1}/><h3>Keep a little<br/>wild in your life.</h3><p>Thoughtfully composed.<br/>Made to be yours.</p><a href={withBase("/shop")} tabIndex={active===4?0:-1}>Begin your chapter ↗</a><span className="diary-publisher">TERRARIUM · FIELD NOTES NO. 01</span></div>
 {[0,1,2,3].map(i=><div key={i} className="diary-sheet" style={{zIndex:10-i}} aria-hidden={active!==i}><div className={`diary-face ${i===0?'diary-cover':'diary-paper'}`}>
 {i===0?<><span className="diary-edition">VOL. 01 / THE ART OF SMALL WORLDS</span><Leaf size={42} strokeWidth={1}/><h3>A world<br/><em>within.</em></h3><div className="cover-rule"/><p>Notes on nature.<br/>Made personal.</p><span className="diary-publisher">TERRARIUM</span></>:<><span className="paper-kicker">TERRARIUM / FIELD NOTES</span><div className="diary-photo"><img src={withBase(['','/lifestyle-desk.jpg','/hero-inside.jpg','/lifestyle-gift.jpg'][i])} alt={['','Terrarium bringing nature to a desk','Ferns and moss inside a terrarium','A terrarium given as a gift'][i]}/></div><span className="handwritten">{['','A little everyday escape.','Beauty is in the details.','Something worth giving.'][i]}</span><h3>{['','Nature, within reach.','Composed with care.','A world of your own.'][i]}</h3><p>{['','We believe the smallest spaces can hold the most extraordinary things.','A living landscape starts with balance. Room for roots, light for leaves, and a little space to grow.','Ready made or customized. A personal piece of nature, for you or someone you love.'][i]}</p><span className="paper-number">0{i}</span></>}
 </div><div className="diary-reverse"/></div>)}
 </div><p className="diary-instruction">SCROLL TO TURN THE PAGES</p></div></div></section>
}
