'use client';
import {withBase} from '@/lib/base-path';
import { useState, useRef, useEffect } from 'react';
import { ArrowUpRight, Sun, Droplets, Sprout, Scan, Wind, Sparkles } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';

export function ForestBreak(){
 const section=useRef<HTMLElement>(null);const img=useRef<HTMLImageElement>(null);
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;let raf=0;const move=()=>{raf=0;if(section.current&&img.current){const r=section.current.getBoundingClientRect();const p=(innerHeight/2-r.top-r.height/2)/innerHeight;img.current.style.transform=`translate3d(0,${Math.max(-70,Math.min(70,p*100))}px,0) scale(1.15)`}};const scroll=()=>{if(!raf)raf=requestAnimationFrame(move)};move();window.addEventListener('scroll',scroll,{passive:true});return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(raf)}},[]);
 return <section className="forest-break" ref={section}><img ref={img} src={withBase("/forest-macro.jpg")} alt="Sunlight falling across moss and delicate fern leaves inside a miniature forest" loading="lazy"/><div className="forest-shade"/><div className="forest-break-copy reveal"><p className="eyebrow">A CHANGE OF SCENERY. WITHOUT GOING ANYWHERE.</p><h2>Big forest<br/><em>energy.</em></h2><a href="#guide" className="button lime-button">Find your natural fit <ArrowUpRight size={18}/></a></div><span className="forest-caption">LOOK CLOSER. THERE’S A WHOLE WORLD HERE.</span><div className="orbit-stamp" aria-hidden="true">A LITTLE<br/><span>WILD</span><br/>BY NATURE ✳</div></section>
}
const fits=[
 {id:'desk',tag:'01 / YOUR DAILY DOSE OF GREEN',title:'Small world. Big desk energy.',copy:'A compact landscape that leaves room for the rest of your day. Choose a vessel you can comfortably reach around and lift.',size:'Mini or small',where:'A bright desk, away from direct sun',image:'desk'},
 {id:'shelf',tag:'02 / MAKE ROOM FOR WONDER',title:'Give that shelf a little life.',copy:'Create a focal point between books, ceramics and your favourite things. Leave space above the vessel to open it and care for the plants.',size:'Small or medium',where:'A stable shelf with suitable light',image:'shelf'},
 {id:'statement',tag:'03 / LET NATURE TAKE CENTRE STAGE',title:'The room’s new conversation starter.',copy:'Go generous with the landscape. Measure the surface, check its weight capacity, and plan how you’ll move the finished piece.',size:'Large or customized',where:'A console, side table or centrepiece',image:'statement'},
 {id:'gift',tag:'04 / GIVE A LITTLE WORLD',title:'A gift that keeps on growing.',copy:'For a colleague, a loved one, or someone who deserves a little green. Choose a thoughtful size and include simple care notes.',size:'A thoughtful gift',where:'A personal gesture, for any occasion',image:'gift'}
];
const faqs=[
 ['What is a terrarium?','A miniature planted garden inside a clear container. Open and closed designs create different conditions, so the plants and vessel need to suit each other.'],
 ['Should I choose an open or closed terrarium?','Closed vessels suit humidity-loving plants such as small ferns and fittonias. Open designs suit plants that prefer drier air, including many succulents.'],
 ['Where should I put it?','For a tropical terrarium, choose bright, indirect light. Avoid hot direct sun on the glass. Check the light needs of the specific plants you choose.'],
 ['How often will I need to water it?','There is no universal schedule. Closed terrariums retain moisture; open ones lose it faster. Check the plants and soil, and follow the care instructions for your arrangement.'],
 ['Is condensation on the glass normal?','Some condensation is expected in a closed terrarium. If the glass stays heavily wet, briefly open it to let excess moisture escape.'],
 ['Can I customize the size and design?','Yes — the collection is designed around ready-made and customized options, from small desk pieces to larger landscapes. Ordering will be available when the store launches.'],
 ['Can I keep it in a room with no daylight?','Living plants still need suitable light. A correctly chosen grow light can help where daylight is insufficient; a dark room alone will not support healthy growth.'],
 ['Does it need any maintenance?','Yes. Check plant health, remove dead material and trim growth when needed. Low-maintenance means less care, not no care.']
];
export function PlantGuide(){const [fit,setFit]=useState('desk');const guide=useRef<HTMLElement>(null);const manual=useRef<number|null>(null);
 useEffect(()=>{let frame=0;const update=()=>{frame=0;if(!guide.current)return;const r=guide.current.getBoundingClientRect();const span=r.height-innerHeight;if(span<=0)return;if(manual.current!==null){if(Math.abs(window.scrollY-manual.current)<6)manual.current=null;else return;}const p=Math.max(0,Math.min(.999,-r.top/span));setFit(fits[Math.floor(p*4)].id)};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};const cancel=()=>{manual.current=null};window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('wheel',cancel,{passive:true});window.addEventListener('touchstart',cancel,{passive:true});update();return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);window.removeEventListener('wheel',cancel);window.removeEventListener('touchstart',cancel)}},[]);
 const selectFit=(id:string)=>{setFit(id);if(!guide.current)return;const index=fits.findIndex(f=>f.id===id);const top=guide.current.getBoundingClientRect().top+window.scrollY;const y=top+(guide.current.offsetHeight-innerHeight)*((index+.12)/4);manual.current=y;window.scrollTo({top:y,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};return <>
 <section className="selection-guide" id="guide" ref={guide}><div className="guide-sticky"><div className="guide-heading reveal"><p className="eyebrow">FIND YOUR NATURAL FIT</p><h2>Your space.<br/>Your kind of <em>wild.</em></h2><p>Start with the spot. Then find a little world that belongs there.</p></div><Tabs value={fit} onValueChange={selectFit} className="fit-tabs"><TabsList className="fit-options" aria-label="Choose a space for your terrarium"><TabsTrigger value="desk">On my desk <span>01</span></TabsTrigger><TabsTrigger value="shelf">On a shelf <span>02</span></TabsTrigger><TabsTrigger value="statement">Make a statement <span>03</span></TabsTrigger><TabsTrigger value="gift">Give a little green <span>04</span></TabsTrigger></TabsList>{fits.map(f=><TabsContent value={f.id} key={f.id}><div className="fit-result"><div className={`fit-image fit-${f.image}`}><img src={withBase(`/lifestyle-${f.image}.jpg`)} alt={{desk:"A terrarium on a light oak work desk",shelf:"A terrarium displayed on a shelf with books and ceramics",statement:"A large terrarium centerpiece in an elegant living room",gift:"A terrarium presented as a thoughtful gift"}[f.image]} loading="eager"/><span className="fit-size">{f.size}</span></div><div className="fit-copy"><p className="eyebrow">{f.tag}</p><h3>{f.title}</h3><p>{f.copy}</p><div className="fit-spec"><Sun size={19}/><span>{f.where}</span></div><a href={withBase("/shop")} className="text-link">Explore the collection <ArrowUpRight size={18}/></a></div></div></TabsContent>)}</Tabs><div className="guide-scroll-note"><span>SCROLL TO FIND YOUR FIT</span><span>0{fits.findIndex(f=>f.id===fit)+1} / 04</span></div></div></section>
 <section className="before-buy" id="care"><div className="section-top reveal"><div><p className="eyebrow">A LITTLE KNOW-HOW GOES A LONG WAY</p><h2>Before you bring<br/><em>nature home.</em></h2></div><span className="section-aside">Four things to think about.<br/>A happier little world.</span></div><div className="care-grid">{[{icon:Sun,no:'01',title:'Follow the light.',text:'Match the plants to your light. Tropical terrariums prefer bright, indirect light.'},{icon:Droplets,no:'02',title:'Choose the climate.',text:'Humid forest or drier desert? Choose plants with similar needs for the same vessel.'},{icon:Scan,no:'03',title:'Measure your moment.',text:'Check the width, height and weight of your spot. Leave room to open, water and trim.'},{icon:Sprout,no:'04',title:'Think beyond day one.',text:'Plants grow. Ask about mature size, pruning and a care routine that fits your life.'}].map(({icon:Icon,...c})=><article className="care-card reveal" key={c.no}><div><Icon size={26} strokeWidth={1.4}/><span>{c.no}</span></div><h3>{c.title}</h3><p>{c.text}</p></article>)}</div>
 <div className="facts-band reveal"><div><Sparkles size={22}/><p className="eyebrow">SMALL WORLD.<br/>SURPRISING FACTS.</p></div><article><span>01</span><h3>A tiny water cycle.</h3><p>Moisture recirculates inside a closed terrarium.</p></article><article><span>02</span><h3>Room to find balance.</h3><p>Larger vessels can be easier to keep balanced than tiny ones.</p></article><article><span>03</span><h3>Still growing. Always.</h3><p>With suitable care, a terrarium can last for years.</p></article></div></section>
 <section className="faq-section" id="faq"><div className="faq-intro reveal"><p className="eyebrow">LET’S CLEAR A FEW THINGS UP</p><h2>Curious<br/>by <em>nature?</em></h2><p>You don’t need a green thumb.<br/>Just a good place to start.</p><a href="#guide" className="text-link">Find your first terrarium <ArrowUpRight size={18}/></a></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger><span className="faq-number">0{i+1}</span>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <div className="care-sources">Care notes: <a href="https://www.rhs.org.uk/plants/types/houseplants/bottle-gardens-and-terrariums" target="_blank" rel="noreferrer">Royal Horticultural Society ↗</a><span>·</span><a href="https://extension.umn.edu/about/our-stories/news/writers-guild-article-terrarium-gardening" target="_blank" rel="noreferrer">University of Minnesota Extension ↗</a></div>
 </>}
