'use client';
import {withBase} from '@/lib/base-path';
import {useEffect,useRef,type RefObject} from 'react';
const smooth=(a:number,b:number,p:number)=>{const t=Math.max(0,Math.min(1,(p-a)/(b-a)));return t*t*(3-2*t)};
export default function HeroPhoto({progress}:{progress:RefObject<number>}){
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{let frame=0,current=progress.current,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const animate=(time:number)=>{const dt=Math.min((time-last)/1000,.05);last=time;current+=(progress.current-current)*(1-Math.exp(-dt*9));const el=root.current;if(el){const enter=smooth(.12,.38,current),rise=smooth(.53,.73,current),turn=smooth(.73,1,current);el.style.setProperty('--enter',String(enter));el.style.setProperty('--rise',String(rise));el.style.setProperty('--front-opacity',String(1-smooth(.23,.37,current)));el.style.setProperty('--inside-opacity',String(smooth(.22,.37,current)*(1-smooth(.57,.72,current))));el.style.setProperty('--top-opacity',String(smooth(.60,.74,current)));el.style.setProperty('--front-scale',String(reduced.matches?1:1+enter*1.35));el.style.setProperty('--inside-scale',String(reduced.matches?1:1.12-enter*.12+rise*.2));el.style.setProperty('--top-scale',String(reduced.matches?1:1.2-rise*.2));el.style.setProperty('--turn',`${reduced.matches?0:turn*110}deg`);el.style.setProperty('--lift',`${reduced.matches?0:rise*-12}%`);}frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[progress]);
 return <div className="photo-journey" ref={root} aria-label="Scroll journey: the whole terrarium, inside the forest, then a clockwise rotating top view" role="img"><div className="journey-shadow"/><img className="journey-front" src={withBase("/hero-front.png")} alt="" width="1206" height="1304" fetchPriority="high"/><div className="journey-inside"><img src={withBase("/hero-inside.jpg")} alt="" width="784" height="1168"/><span>WITHIN THE GLASS</span></div><div className="journey-top"><img src={withBase("/hero-top.png")} alt="" width="1024" height="1024"/></div><div className="journey-caption"><span>ONE LITTLE WORLD</span><span>THREE PERSPECTIVES</span></div></div>
}
