'use client';
import {withBase} from '@/lib/base-path';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, ChevronDown, ArrowLeft, ArrowRight, Leaf } from 'lucide-react';
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink } from '@/components/ui/navigation-menu';
import TerrariumScene from './terrarium-scene';
import HeroPhoto from './hero-photo';
import AboutDiary from './about-diary';
import CustomerReviews from './customer-reviews';
import { ForestBreak, PlantGuide } from './explore-sections';
const chapters = [
 {tag:'A LITTLE WORLD. A SLOWER MOMENT.', title:<>Nature, in<br/>its own <em>world.</em></>, text:'Living landscapes, thoughtfully made. Bring a little wilderness into your everyday.',label:'The whole little world',detail:'01 / A different kind of green'},
 {tag:'LOOK A LITTLE CLOSER.',title:<>Small leaves.<br/><em>Infinite wonder.</em></>,text:'A canopy of delicate ferns. A carpet of soft moss. Every detail invites you to pause.',label:'Among the leaves',detail:'02 / Beauty in the details'},
 {tag:'A FRESH PERSPECTIVE.',title:<>A world worth<br/><em>looking into.</em></>,text:'Ferns, moss and stone. A living composition, beautiful from every perspective.',label:'A view from above',detail:'03 / A fresh perspective'}
];
export default function Home(){
 const story=useRef<HTMLElement>(null); const progress=useRef(0); const [chapter,setChapter]=useState(0); 
 useEffect(()=>{const scroll=()=>{if(!story.current)return; const r=story.current.getBoundingClientRect(); progress.current=Math.max(0,Math.min(1,-r.top/(r.height-innerHeight)));setChapter(progress.current<.30?0:progress.current<.66?1:2);document.documentElement.style.setProperty("--page-progress",`${window.scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100}%`);};scroll();window.addEventListener('scroll',scroll,{passive:true});const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal, .faq-list, .footer-top, .footer-word').forEach(e=>{e.classList.add('reveal');observer.observe(e)});return()=>{window.removeEventListener('scroll',scroll);observer.disconnect()};},[]);
 return <main><div className="reading-progress" aria-hidden="true"/>
 <header className="header"><a className="brand" href="#home"><Leaf size={24} strokeWidth={1.4}/> Terrarium<span>✳</span></a><nav aria-label="Main navigation"><a href="#home">Home</a><a href="#about">About</a><NavigationMenu viewport={false} delayDuration={100} className="shop-navigation" aria-label="Shop categories"><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger className="nav-shop">Shop</NavigationMenuTrigger><NavigationMenuContent className="shop-flyout"><p className="menu-eyebrow">FIND YOUR LITTLE WORLD</p><NavigationMenuLink asChild><a href={withBase("/shop?category=customized")}><span>Customized <ArrowUpRight size={17}/></span><small>A world designed around you.</small></a></NavigationMenuLink><NavigationMenuLink asChild><a href={withBase("/shop?category=ready-made")}><span>Ready made <ArrowUpRight size={17}/></span><small>Thoughtfully composed, ready to love.</small></a></NavigationMenuLink></NavigationMenuContent></NavigationMenuItem></NavigationMenuList></NavigationMenu><a href="#contact">Contact</a></nav><a className="header-cta" href={withBase("/shop")}>Find your little world <ArrowUpRight size={16}/></a></header>
 <section className="story photo-story" ref={story} id="home"><div className="story-sticky" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--pointer-x",`${e.clientX-r.left}px`);e.currentTarget.style.setProperty("--pointer-y",`${e.clientY-r.top}px`)}}><div className="hero-wash"/><div className="hero-copy" key={chapter}><p className="eyebrow"><span/> {chapters[chapter].tag}</p><h1>{chapters[chapter].title}</h1><p className="intro">{chapters[chapter].text}</p><a href={withBase("/shop")} className="button">Explore our worlds <ArrowUpRight size={18}/></a><div className="hero-note"><span>Handcrafted by nature.<br/>Made personal by us.</span><span className="note-line"/></div></div><div className="scene-wrap"><HeroPhoto progress={progress}/><div className="specimen-label"><span className="specimen-number">0{chapter+1}</span><div key={chapter}><span className="specimen-kicker">FIELD NOTES</span><strong>{chapters[chapter].label}</strong><small>{["A forest, beautifully contained.","Delicate fronds. Extraordinary detail.","Every detail, beautifully connected."][chapter]}</small></div></div></div><div className="hero-bottom"><a href="#about"><ArrowDown size={16}/> Scroll to discover</a><div className="chapter-dots">{chapters.map((c,i)=><button key={i} aria-label={`View ${c.label}`} aria-current={chapter===i?'step':undefined} className={chapter===i?'active':''} onClick={()=>{const s=story.current;if(s)window.scrollTo({top:s.offsetTop+(s.offsetHeight-innerHeight)*([.02,.46,.9][i]),behavior:'smooth'})}}/>)}<span>{chapters[chapter].detail}</span></div><span className="hero-side-note">NATURE. ON A SMALLER SCALE.</span></div></div></section>
 <div className="energy-ribbon" aria-hidden="true"><div>{[0,1,2,3].map(i=><span key={i}>A LITTLE WILD <b>✳</b> A LOT OF LIFE <b>✳</b> MADE FOR YOUR WORLD <b>✳</b></span>)}</div></div>
 <AboutDiary/>
 <section className="about about-energized living-gallery"><div className="about-copy reveal"><p className="eyebrow">THE LIVING GALLERY</p><h2>A whole new<br/><em>perspective.</em></h2><p>Turn it. Tilt it. Discover a miniature forest from every angle.</p><a href={withBase("/shop")} className="text-link">Explore our collection <ArrowUpRight size={18}/></a></div><div className="about-viewer reveal"><TerrariumScene/></div></section>
 <ForestBreak/>
 <section className="shop-section" id="shop"><div className="shop-heading reveal"><div><p className="eyebrow">YOUR LITTLE WORLD AWAITS</p><h2>Find your kind<br/>of <em>green.</em></h2></div><p>A quiet corner. A thoughtful gift.<br/>A world made just for you.<br/>There’s a terrarium for every space.</p></div><div className="shop-grid"><article className="shop-card reveal" id="ready-made"><div className="shop-photo"><img src={withBase("/terrarium.jpg")} alt="A handcrafted glass terrarium filled with ferns, moss and natural stone"/><span className="card-tag">READY TO FALL IN LOVE</span><span className="card-index">01</span></div><div className="card-bottom"><div><h3>Nature, ready made.</h3><p>Thoughtfully composed. Ready for your space.</p></div><a className="round-button" href={withBase("/shop?category=ready-made")} aria-label="Shop ready-made terrariums"><ArrowUpRight/></a></div><div className="sizes">MINI <span/> SMALL <span/> MEDIUM <span/> LARGE</div></article><article className="shop-card custom reveal" id="customized"><div className="shop-photo"><img src={withBase("/terrarium.jpg")} alt="Close-up of the lush miniature landscape, inspiration for a custom terrarium"/><span className="card-tag">DREAM IT. WE’LL GROW IT.</span><span className="card-index">02</span><div className="custom-overlay">Your vision.<br/><em>Your little world.</em></div></div><div className="card-bottom"><div><h3>A world of your own.</h3><p>Your size. Your style. Your piece of nature.</p></div><a className="round-button" href={withBase("/shop?category=customized")} aria-label="Shop customized terrariums"><ArrowUpRight/></a></div><div className="sizes">PERSONALIZED <span/> ANY SIZE <span/> ONE OF A KIND</div></article></div><div className="shop-cta reveal"><span>Big on wonder. In every size.</span><a href={withBase("/shop")} className="button">Shop now <ArrowUpRight size={18}/></a></div></section>
 <PlantGuide/>
 <CustomerReviews/>
 <footer id="contact"><div className="footer-top"><div><a className="brand" href="#home"><Leaf size={24} strokeWidth={1.4}/> Terrarium<span>✳</span></a><p>A little nature.<br/>A whole new feeling.</p></div><div className="footer-links"><p>EXPLORE</p><a href="#home">Home</a><a href="#about">Our story</a><a href={withBase("/shop")}>The collection</a></div><div className="footer-links"><p>YOUR TERRARIUM</p><a href={withBase("/shop?category=ready-made")}>Ready made</a><a href={withBase("/shop?category=customized")}>Customized</a><a href="#guide">Find your fit</a><a href="#care">Care & buying tips</a><a href="#faq">FAQs</a></div><div className="footer-contact"><p>LET’S GROW SOMETHING</p><span>Contact details to be added</span><span className="muted">Your next little world starts here.</span></div></div><div className="footer-word">a world within.</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Terrarium. All rights reserved.</span><span>Made with care. Inspired by nature.</span><a href="#home">Back to top ↑</a></div></footer>
 </main>
}

