'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { TrackballControls } from 'three/addons/controls/TrackballControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { RotateCcw, Pause, Play, Plus, Minus, Move } from 'lucide-react';
const models={forest:{url:'/models/forest-in-a-jar.glb',name:'Forest in a Jar',author:'kairo.german',source:'https://sketchfab.com/3d-models/forest-in-a-jar-e33dece0424e4888836aa903c2630e57'},garden:{url:'/models/miniature-garden.glb',name:'Miniature garden',author:'tony428tw',source:'https://sketchfab.com/3d-models/114-1cyut-bb2aae4c26cc4d33bb22928ea7df168f'}};
type ModelKey=keyof typeof models;
function disposeModel(root:THREE.Object3D){const mats=new Set<THREE.Material>();const tex=new Set<THREE.Texture>();root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m))}});mats.forEach(m=>{Object.values(m).forEach(v=>{if(v instanceof THREE.Texture)tex.add(v)});m.dispose()});tex.forEach(t=>{if(typeof ImageBitmap!=='undefined'&&t.image instanceof ImageBitmap)t.image.close();t.dispose()})}
function GLBStage({model,immersive=false}:{model:ModelKey,immersive?:boolean}){
 const host=useRef<HTMLDivElement>(null);const pausedRef=useRef(false);const [paused,setPaused]=useState(false);const [status,setStatus]=useState('loading');const [percent,setPercent]=useState(0);const [retry,setRetry]=useState(0);
 const api=useRef<{reset:()=>void;zoom:(n:number)=>void}|null>(null);const entry=models[model];
 useEffect(()=>{pausedRef.current=paused},[paused]);
 useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:THREE.WebGLRenderer;let disposed=false;setStatus('loading');setPercent(0);
 try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});}catch{setStatus('unavailable');return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(immersive?0x10251b:0xffffff,immersive?1:0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.72;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(immersive?52:34,1,.02,100);const controls=new TrackballControls(camera,renderer.domElement);controls.rotateSpeed=2.5;controls.noPan=!immersive;controls.noZoom=!immersive;controls.zoomSpeed=.7;controls.dynamicDampingFactor=.12;controls.minDistance=immersive?.35:3.1;controls.maxDistance=12;
 const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);room.dispose();scene.environment=environment.texture;
 scene.add(new THREE.HemisphereLight(0xffffff,0x263020,.65));const key=new THREE.DirectionalLight(0xfff4df,1.45);key.position.set(-3,5,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.bias=-.001;key.shadow.normalBias=.025;scene.add(key);const fill=new THREE.DirectionalLight(0xe0f1ff,.3);fill.position.set(4,3,-3);scene.add(fill);
 const world=new THREE.Group();scene.add(world);let loaded:THREE.Object3D|null=null,visible=true,dragging=false,frame=0,last=0;const home=new THREE.Vector3(0,.35,6.4);camera.position.copy(home);controls.target.set(0,0,0);controls.update();
 const reset=()=>{controls.reset();world.rotation.set(0,0,0);camera.position.copy(home);camera.up.set(0,1,0);controls.target.set(0,0,0);controls.update()};const zoom=(n:number)=>{const delta=camera.position.clone().sub(controls.target);camera.position.copy(controls.target.clone().add(delta.setLength(THREE.MathUtils.clamp(delta.length()*n,immersive?.4:3.1,12))));controls.update()};api.current={reset,zoom};
 const loader=new GLTFLoader();loader.load(entry.url,gltf=>{if(disposed){disposeModel(gltf.scene);return}loaded=gltf.scene;loaded.updateMatrixWorld(true);const box=new THREE.Box3();
 loaded.traverse(o=>{if(o instanceof THREE.Mesh){const mats=Array.isArray(o.material)?o.material:[o.material];o.castShadow=!mats.some(m=>m.transparent);o.receiveShadow=true;const background=mats.some(m=>/background/i.test(m.name));if(!background){o.geometry.computeBoundingBox();if(o.geometry.boundingBox)box.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld))}mats.forEach(m=>{if(m.transparent)m.depthWrite=false;if(m instanceof THREE.MeshStandardMaterial){m.envMapIntensity=.16;m.emissiveIntensity=.35;}});}});
 if(box.isEmpty())box.setFromObject(loaded);const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const scale=3.2/Math.max(size.x,size.y,size.z);const normalized=new THREE.Group();normalized.add(loaded);loaded.position.sub(center);normalized.scale.setScalar(scale);world.add(normalized);const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,12),new THREE.ShadowMaterial({opacity:.3}));floor.rotation.x=-Math.PI/2;floor.position.y=-size.y*scale/2-.04;floor.receiveShadow=true;scene.add(floor);
 const aspect=el.clientWidth/Math.max(1,el.clientHeight),fov=camera.fov*Math.PI/180;const distance=Math.max(size.y*scale/(2*Math.tan(fov/2)),size.x*scale/(2*Math.tan(fov/2)*aspect))*1.08+size.z*scale*.5;
 home.set(immersive?distance*.18:0,immersive?distance*.18:distance*.035,distance);camera.position.copy(home);controls.update();setStatus('ready');
 },event=>{if(!disposed&&event.total)setPercent(Math.round(event.loaded/event.total*100))},()=>{if(!disposed)setStatus('error')});
 const start=()=>{dragging=true};const end=()=>{dragging=false};controls.addEventListener('start',start);controls.addEventListener('end',end);
 const keyboard=(e:KeyboardEvent)=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home'].includes(e.key)){e.preventDefault();if(e.key==='Home')reset();else if(e.key==='+')zoom(.9);else if(e.key==='-')zoom(1.1);else{world.rotation.y+=e.key==='ArrowLeft'?-.14:e.key==='ArrowRight'?.14:0;world.rotation.x+=e.key==='ArrowUp'?-.14:e.key==='ArrowDown'?.14:0}}};el.addEventListener('keydown',keyboard);
 const lost=(e:Event)=>{e.preventDefault();setStatus('unavailable')};renderer.domElement.addEventListener('webglcontextlost',lost);
 const resize=()=>{if(!el.clientWidth||!el.clientHeight)return;renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();controls.handleResize()};const ro=new ResizeObserver(resize);ro.observe(el);resize();const io=new IntersectionObserver(es=>{visible=es[0].isIntersecting});io.observe(el);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const animate=(time:number)=>{frame=requestAnimationFrame(animate);const dt=Math.min((time-last)/1000,.05);last=time;if(!visible||document.hidden)return;if(!pausedRef.current&&!reduced&&!dragging)world.rotation.y+=dt*(immersive?.035:.13);controls.update();renderer.render(scene,camera)};frame=requestAnimationFrame(animate);
 return()=>{disposed=true;cancelAnimationFrame(frame);ro.disconnect();io.disconnect();el.removeEventListener('keydown',keyboard);renderer.domElement.removeEventListener('webglcontextlost',lost);controls.dispose();api.current=null;if(loaded)disposeModel(loaded);scene.traverse(o=>{if(o instanceof THREE.Mesh&&o.material instanceof THREE.ShadowMaterial){o.geometry.dispose();o.material.dispose()}});environment.dispose();pmrem.dispose();renderer.dispose();renderer.domElement.remove()};
 },[model,immersive,retry,entry.url]);
 return <><div className={`studio-canvas ${immersive?'immersive-canvas':''}`} ref={host} tabIndex={0} role="region" aria-label={`${entry.name} interactive 3D viewer. Drag in any direction. Arrow keys rotate; plus and minus zoom; Home resets.`}>{status!=='ready'&&<div className="viewer-message" role="status">{status==='loading'?<><span className="loading-orbit"/><strong>Growing your little world…</strong><span>{percent?`${percent}%`:'Loading 3D details'}</span></>:<><img src="/terrarium-cutout.png" alt="Terrarium photo — 3D preview unavailable"/><p>{status==='unavailable'?'Enable WebGL in your browser to explore the 3D model.':'The model could not load. Please try again.'}</p>{status==='error'&&<button onClick={()=>setRetry(v=>v+1)}>Try again</button>}</>}</div>}</div><div className="studio-bottom"><span><Move size={15}/>{status==='ready'?(immersive?'Drag to look around · scroll to move closer':'Drag to explore · all directions'):status==='loading'?'Loading your model':'Photo fallback'}</span><div><button disabled={status!=='ready'} aria-label="Zoom in" onClick={()=>api.current?.zoom(.85)}><Plus size={16}/></button><button disabled={status!=='ready'} aria-label="Zoom out" onClick={()=>api.current?.zoom(1.15)}><Minus size={16}/></button><button disabled={status!=='ready'} aria-label="Reset 3D view" onClick={()=>api.current?.reset()}><RotateCcw size={16}/></button><button disabled={status!=='ready'} aria-label={paused?'Resume rotation':'Pause rotation'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button></div></div><p className="model-credit"><a href={entry.source} target="_blank" rel="noreferrer">{entry.name}</a> by {entry.author} · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a></p></>;
}
export default function TerrariumScene(){const root=useRef<HTMLDivElement>(null);const [active,setActive]=useState(false);useEffect(()=>{if(!root.current)return;const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){setActive(true);io.disconnect()}},{rootMargin:'250px'});io.observe(root.current);return()=>io.disconnect()},[]);return <div className="terrarium-studio" ref={root}><div className="studio-top"><span className="eyebrow">THE LIVING GALLERY</span><span className="studio-badge">360° INTERACTIVE</span></div>{active?<GLBStage model="forest"/>:<div className="studio-canvas" aria-label="3D viewer loads as you approach"/>}</div>}
