'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Search,SlidersHorizontal,X,Leaf} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {products,type Product} from './products';
const money=(value:number)=>`AED ${value}`;
export default function Shop(){const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[sizes,setSizes]=useState<string[]>([]),[budget,setBudget]=useState('all'),[sort,setSort]=useState('featured'),[filtersOpen,setFiltersOpen]=useState(false),[selected,setSelected]=useState<Product|null>(null);
 useEffect(()=>{const c=new URLSearchParams(window.location.search).get('category');if(c==='customized'||c==='ready-made')setCategory(c)},[]);
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();let list=products.filter(p=>(!q||`${p.name} ${p.subtitle} ${p.description} ${p.size}`.toLowerCase().includes(q))&&(category==='all'||p.category===category)&&(!sizes.length||sizes.includes(p.size))&&(budget==='all'||(budget==='under200'?p.price<200:budget==='200to350'?p.price>=200&&p.price<=350:p.price>350)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list},[query,category,sizes,budget,sort]);
 const clear=()=>{setQuery('');setCategory('all');setSizes([]);setBudget('all')};const count=sizes.length+(category!=='all'?1:0)+(budget!=='all'?1:0);
 return <main className="store"><header className="store-header"><a href="/" className="brand"><Leaf size={25}/>Terrarium<span>✳</span></a><nav aria-label="Main navigation"><a href="/">Home</a><a href="/#about">About</a><a href="/shop" aria-current="page">Shop</a><a href="/#contact">Contact</a></nav><a className="store-guide-link" href="/#guide">Find your natural fit <ArrowUpRight size={15}/></a></header>
 <section className="store-intro"><div><a className="store-breadcrumb" href="/"><ArrowLeft size={14}/> BACK TO OUR WORLD</a><p className="eyebrow">THE TERRARIUM COLLECTION</p><h1>Find your<br/>kind of <em>green.</em></h1><p>For your desk. For your favourite person.<br/>For a little more life, wherever you are.</p></div><div className="store-intro-photo"><img src="/hero-top.png" alt="A view into a terrarium filled with ferns, moss and stones"/><span>SMALL WORLDS.<br/>ENDLESS POSSIBILITIES.</span></div></section>
 <div className="store-preview-note">Collection preview · Sample products, images and AED prices. Online ordering is not available yet.</div>
 <section className="catalog" aria-label="Shop terrariums"><div className="catalog-toolbar"><label className="catalog-search"><Search size={19}/><span className="sr-only">Search terrariums</span><input type="search" placeholder="Find your little world…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={17}/></button>}</label><div className="catalog-sort"><label id="sort-label">Sort by</label><Select value={sort} onValueChange={setSort}><SelectTrigger aria-labelledby="sort-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="featured">Featured</SelectItem><SelectItem value="low">Price: low to high</SelectItem><SelectItem value="high">Price: high to low</SelectItem><SelectItem value="name">Name: A–Z</SelectItem></SelectContent></Select></div><button className="mobile-filter-toggle" aria-expanded={filtersOpen} aria-controls="catalog-filters" onClick={()=>setFiltersOpen(v=>!v)}><SlidersHorizontal size={17}/>Filters {count>0&&`(${count})`}</button></div>
 <div className="catalog-layout"><aside className={`catalog-filters ${filtersOpen?'filters-open':''}`} id="catalog-filters"><div className="filter-heading"><h2>Find your fit</h2><button onClick={clear}>Reset</button></div><fieldset><legend>Collection</legend>{[['all','All little worlds'],['ready-made','Ready made'],['customized','Customized']].map(([v,label])=><button className="category-filter" key={v} aria-pressed={category===v} onClick={()=>setCategory(v)}><span>{label}</span><span>{v==='all'?products.length:products.filter(p=>p.category===v).length}</span></button>)}</fieldset><fieldset><legend>Size</legend>{['Mini','Small','Medium','Large'].map(size=><label className="size-filter" key={size}><Checkbox checked={sizes.includes(size)} onCheckedChange={checked=>setSizes(v=>checked?[...v,size]:v.filter(s=>s!==size))}/><span>{size}</span></label>)}</fieldset><fieldset><legend id="budget-label">Budget</legend><Select value={budget} onValueChange={setBudget}><SelectTrigger aria-labelledby="budget-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Any price</SelectItem><SelectItem value="under200">Under AED 200</SelectItem><SelectItem value="200to350">AED 200–350</SelectItem><SelectItem value="over350">Over AED 350</SelectItem></SelectContent></Select></fieldset><div className="catalog-help"><Leaf size={23}/><h3>Not sure where<br/>to start?</h3><p>Find a world that feels at home in your space.</p><a href="/#guide">Explore our guide <ArrowUpRight size={16}/></a></div></aside>
 <div className="catalog-results"><div className="results-heading"><p role="status">{visible.length} little {visible.length===1?'world':'worlds'}{query&&` matching “${query}”`}</p><span>GROWN IN IMAGINATION. MADE WITH CARE.</span></div>{count>0&&<div className="active-filters">{category!=='all'&&<button onClick={()=>setCategory('all')}>{category==='ready-made'?'Ready made':'Customized'} <X size={12}/></button>}{sizes.map(s=><button key={s} onClick={()=>setSizes(v=>v.filter(x=>x!==s))}>{s}<X size={12}/></button>)}{budget!=='all'&&<button onClick={()=>setBudget('all')}>Budget filter <X size={12}/></button>}<button onClick={clear}>Clear all</button></div>}
 <div className="product-grid">{visible.map((p,i)=><article className="product-card" key={p.id} style={{animationDelay:`${Math.min(i,5)*45}ms`}}><button className={`product-photo ${p.image.endsWith('.png')?'product-cutout':''}`} onClick={()=>setSelected(p)} aria-label={`View ${p.name}`}><img src={p.image} alt={p.name} loading="lazy"/><span className="product-tag">{p.tag}</span><span className="product-quick">Take a closer look <ArrowUpRight size={17}/></span></button><div className="product-meta"><span>{p.category==='customized'?'CUSTOMIZED':'READY MADE'}</span><span>{p.size}</span></div><button className="product-name" onClick={()=>setSelected(p)}><h2>{p.name}</h2></button><p>{p.subtitle}</p><div className="product-bottom"><strong>{p.category==='customized'&&<small>From </small>}{money(p.price)}</strong><button aria-label={`View details for ${p.name}`} onClick={()=>setSelected(p)}><ArrowUpRight size={19}/></button></div></article>)}</div>
 {visible.length===0&&<div className="catalog-empty"><Leaf size={42} strokeWidth={1}/><h2>No little worlds found.</h2><p>Try another search or give your filters a little more room.</p><button className="button" onClick={clear}>Reset search & filters</button></div>}</div></div></section>
 <section className="store-closing"><p className="eyebrow">A LITTLE GUIDANCE</p><h2>Good things grow<br/>in the <em>right place.</em></h2><a className="button" href="/#care">Before you bring one home <ArrowUpRight size={18}/></a></section><footer className="store-footer"><a className="brand" href="/">Terrarium ✳</a><span>A little nature. A whole new feeling.</span><a href="/#contact">Contact & enquiries ↗</a><small>© {new Date().getFullYear()} Terrarium</small></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="product-dialog">{selected&&<><img className={selected.image.endsWith('.png')?'detail-cutout':''} src={selected.image} alt={selected.name}/><div className="product-detail-copy"><p className="eyebrow">{selected.category==='customized'?'YOUR WORLD, YOUR WAY':'A LITTLE WORLD, READY MADE'}</p><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><strong className="detail-price">{selected.category==='customized'?'From ':''}{money(selected.price)}</strong><dl><div><dt>Size</dt><dd>{selected.size}</dd></div><div><dt>Dimensions</dt><dd>{selected.dimensions}</dd></div><div><dt>Placement</dt><dd>Bright, indirect light</dd></div></dl><p className="detail-note">Sample listing and indicative price. Final products, care details and availability will be confirmed when the store opens.</p><span className="store-not-open">Online ordering coming soon</span><a href="/#care" className="text-link">Read our buying guide <ArrowUpRight size={15}/></a></div></>}</DialogContent></Dialog>
 </main>
}
