export type Product={id:string;name:string;subtitle:string;category:'ready-made'|'customized';size:string;price:number;image:string;tag:string;description:string;dimensions:string};
export const products:Product[]=[
{id:'woodland',name:'The Woodland Jar',subtitle:'A forest, beautifully contained.',category:'ready-made',size:'Medium',price:245,image:'/hero-front.png',tag:'Signature world',description:'A fern-filled glass jar with moss, natural stones and a layered earth base. A considered focal point for a bright corner.',dimensions:'Approx. 22 × 32 cm'},
{id:'desk',name:'The Desk Companion',subtitle:'A small pause in a busy day.',category:'ready-made',size:'Small',price:145,image:'/lifestyle-desk.jpg',tag:'For your everyday',description:'A compact green landscape for your workspace. Designed to sit comfortably alongside your books, notes and everyday essentials.',dimensions:'Approx. 16 × 18 cm'},
{id:'shelf',name:'The Shelf Garden',subtitle:'Make room for something living.',category:'ready-made',size:'Medium',price:225,image:'/lifestyle-shelf.jpg',tag:'A quiet favourite',description:'A lush glass garden that brings a natural focal point to a shelf or side table. Leave enough room above the opening for care.',dimensions:'Approx. 24 × 25 cm'},
{id:'gift',name:'A Little Green Gift',subtitle:'For someone who means a lot.',category:'ready-made',size:'Small',price:175,image:'/lifestyle-gift.jpg',tag:'Thoughtfully given',description:'A small terrarium concept for colleagues, friends and loved ones. A lasting reminder of a thoughtful moment.',dimensions:'Approx. 18 × 20 cm'},
{id:'statement',name:'The Living Centrepiece',subtitle:'A little wild. A big impression.',category:'ready-made',size:'Large',price:425,image:'/lifestyle-statement.jpg',tag:'Room to grow',description:'A generous statement landscape for a console or spacious table. A sculptural meeting of glass, green and natural stone.',dimensions:'Approx. 35 × 40 cm'},
{id:'pocket',name:'The Pocket Forest',subtitle:'Little space. Plenty of wonder.',category:'ready-made',size:'Mini',price:95,image:'/terrarium-cutout.png',tag:'Start small',description:'A miniature interpretation of our woodland jar for smaller spaces. An easy starting point for choosing your first little world.',dimensions:'Approx. 10 × 14 cm'},
{id:'custom',name:'Your Own Little World',subtitle:'Imagined by you. Composed with care.',category:'customized',size:'Medium',price:295,image:'/hero-top.png',tag:'Made personal',description:'Start with a medium vessel and explore a composition inspired by your space. Final plants, dimensions and price would be confirmed before ordering.',dimensions:'Size tailored to your brief'},
{id:'custom-large',name:'The Bespoke Landscape',subtitle:'Your vision, on a grander scale.',category:'customized',size:'Large',price:595,image:'/hero-inside.jpg',tag:'One of a kind',description:'A larger custom landscape concept. Choose the feeling, the space and the details that matter to you; the final design would be agreed before ordering.',dimensions:'Size tailored to your brief'}
];
